### PR TITLE
Reapply signature filter changes on top of 6.1.1

### PR DESCRIPTION
**Pull request by thomshutt**
This is taking the bits we want to keep from the previous Ffmpeg fork (https://github.com/livepeer/FFmpeg/compare/dc91b913b6260e85e1304c74ff7bb3c22a8c9fb1...2e18d069668c143f3c251067abd25389e411d022) and applying them on top of a new fork from the most recent commit

### CODE REVIEW

**Comment by thomshutt** [comment]
Note: Currently, go-livepeer fails to transcode with this build with the error ```Changing video frame properties on the fly is not supported by all filters```

**Review by leszko — COMMENTED** [review]
@thomshutt what is the context for this change? Why do we do? 🙃 Is it just to be more up-to-date with the ffmpeg main repo?

**Comment by thomshutt** [comment]
@leszko Yep, to get the benefits of more recent FFMPEG changes and hopefully make any future changes that we need to do easier

**Review by leszko — APPROVED** [review]

**Comment by Tibia2000** [comment]
> Note: Currently, go-livepeer fails to transcode with this build with the error `Changing video frame properties on the fly is not supported by all filters`

I am having the same error on current go livepeer version transcoder too, seems to not cause any problems, transcoding is being done : Changing video frame properties on the fly is not supported by all filters.

**Pull request closed without merging**
